version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: todo_app
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_app"]
      interval: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: todo-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todos
      SPRING_DATASOURCE_USERNAME: todo_app
      SPRING_DATASOURCE_PASSWORD: secret
      JWT_SECRET: changemeinprod
    ports:
      - "8080:8080"

volumes:
  pgdata:
